version: '3'
services:
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - backend
  web:
    build:
      context: .
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
    networks:
      - backend

volumes:
  data:
    driver: local

networks:
  backend:
